# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-21 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0003_auto_20190619_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quora.User')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quora.Post')),
            ],
        ),
    ]
