# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-21 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0006_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
    ]
