# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-21 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0007_auto_20190621_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ManyToManyField(to='quora.Post'),
        ),
    ]
