# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-26 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0008_auto_20190621_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_likes',
            new_name='likes',
        ),
    ]
