# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-06-26 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
