# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-02 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quora', '0016_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commented_by',
            new_name='by',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='liked_by',
            new_name='by',
        ),
    ]
